easy_admin:
#    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'
    site_name: 'Craft Betting'

    design:
        assets:
            favicon: '/build/favicon/favicon.png'
        menu:
            - label: 'gérer les pronostics'
            - { entity: 'Prono', icon: 'newspaper', label: 'Pronos Simples' }
            - { entity: 'PronoSur', icon: 'newspaper', label: 'Prono Sûr Du Jour (hp)' }
            - { entity: 'PronoComboSafe', icon: 'newspaper', label: 'Pronos Combo Sûrs (hp)' }
            - { entity: 'PronoComboRisky', icon: 'newspaper', label: 'Pronos Combo Risqués (hp)' }

            - label: 'gérer les statistiques'
            - { entity: 'ChartCurve', icon: 'chart-area', label: 'Toutes les statistiques' }

            - label: 'gérer les sites partenaires'
            - label: 'Sites Web et Adresses'
              icon: 'folder'
              children:
                - { entity: 'Website', icon: 'paperclip', label: 'Sites Web' }
                - { entity: 'WebsiteUrl', icon: 'link', label: 'Adresses des Sites Web' }
#
            - label: 'gérer les utilisateurs'
            - { entity: 'User', icon: 'user', label: 'Utilisateurs' }

    formats:
        date: 'd/m/Y'
        time: 'h:i'

    entities:
        Prono:
            class: App\Entity\Prono
            label: 'Pronostics Simples'
            list:
                title: 'Liste des pronostics'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'date', label: 'Date' }
                    - { property: 'time', label: 'Horaire', format: 'H:i' }
                    - { property: 'countryAndLeague', label: 'Pays et Ligue' }
                    - { property: 'homeTeam', label: 'Domicile' }
                    - { property: 'visitorTeam', label: 'Éxterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site Web' }
                    - { property: 'websiteUrl', label: 'Adresse Site Web' }
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Éditer' }
                    - { name: 'new',  label: 'Ajouter' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'date', label: 'Date', type: 'birthday', type_options: {widget: 'single_text'}}
                    - { property: 'time', label: 'Heure'}
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'countryAndLeague', label: 'Championnat' }
                    - { property: 'homeTeam', label: 'Équipe à domicile' }
                    - { property: 'visitorTeam', label: 'Équipe à l''exterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site' }
                    - { property: 'websiteUrl', label: 'Adresse du site' }
                    - { property: 'analysis', type: 'textarea',  label: 'Analyse' }

        PronoSur:
            class: App\Entity\PronoSur
            label: 'Pronostics Sûrs'
            list:
                title: 'Liste des pronostics Sûrs'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'date', label: 'Date' }
                    - { property: 'time', label: 'Horaire', format: 'H:i' }
                    - { property: 'countryAndLeague', label: 'Pays et Ligue' }
                    - { property: 'homeTeam', label: 'Domicile' }
                    - { property: 'visitorTeam', label: 'Éxterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site Web' }
                    - { property: 'websiteUrl', label: 'Adresse Site Web' }
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Éditer' }
                    - { name: 'new',  label: 'Ajouter' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'date', label: 'Date', type: 'birthday', type_options: {widget: 'single_text'}}
                    - { property: 'time', label: 'Heure'}
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'countryAndLeague', label: 'Championnat' }
                    - { property: 'homeTeam', label: 'Équipe à domicile' }
                    - { property: 'visitorTeam', label: 'Équipe à l''exterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site' }
                    - { property: 'websiteUrl', label: 'Adresse du site' }
                    - { property: 'analysis', type: 'textarea',  label: 'Analyse' }

        PronoComboSafe :
            class: App\Entity\PronoComboSafe
            label: 'Pronostics Combo Sûrs'
            list:
                title: 'Liste Des Combo Sûrs'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'date', label: 'Date' }
                    - { property: 'time', label: 'Horaire', format: 'H:i' }
                    - { property: 'countryAndLeague', label: 'Pays et Ligue' }
                    - { property: 'homeTeam', label: 'Domicile' }
                    - { property: 'visitorTeam', label: 'Éxterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site Web' }
                    - { property: 'websiteUrl', label: 'Adresse Site Web' }
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Éditer' }
                    - { name: 'new',  label: 'Ajouter' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'date', label: 'Date', type: 'birthday', type_options: {widget: 'single_text'}}
                    - { property: 'time', label: 'Heure'}
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'countryAndLeague', label: 'Championnat' }
                    - { property: 'homeTeam', label: 'Équipe à domicile' }
                    - { property: 'visitorTeam', label: 'Équipe à l''exterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site' }
                    - { property: 'websiteUrl', label: 'Adresse du site' }
                    - { property: 'analysis', type: 'textarea',  label: 'Analyse' }

        PronoComboRisky:
            class: App\Entity\PronoComboRisky
            label: 'Pronostics Combo Risqués'
            list:
                title: 'Liste Des Combo Risqués'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'date', label: 'Date' }
                    - { property: 'time', label: 'Horaire', format: 'H:i' }
                    - { property: 'countryAndLeague', label: 'Pays et Ligue' }
                    - { property: 'homeTeam', label: 'Domicile' }
                    - { property: 'visitorTeam', label: 'Éxterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site Web' }
                    - { property: 'websiteUrl', label: 'Adresse Site Web' }
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Éditer' }
                    - { name: 'new',  label: 'Ajouter' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'date', label: 'Date', type: 'birthday', type_options: {widget: 'single_text'}}
                    - { property: 'time', label: 'Heure'}
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'countryAndLeague', label: 'Championnat' }
                    - { property: 'homeTeam', label: 'Équipe à domicile' }
                    - { property: 'visitorTeam', label: 'Équipe à l''exterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site' }
                    - { property: 'websiteUrl', label: 'Adresse du site' }
                    - { property: 'analysis', type: 'textarea',  label: 'Analyse' }

        ChartCurve:
            class: App\Entity\ChartCurve
            label: 'Courbe De Cagnotte'
            list:
                title: 'Liste Des Courbe De Cagnotte'
                fields:
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'date', label: 'Date' }
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Éditer' }
                    - { name: 'new',  label: 'Ajouter' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'date', label: 'Date', type: 'birthday', type_options: {widget: 'single_text' }}
                    - { property: 'odd', label: 'Cote', type: 'number' }
                    - { property: 'result', label: 'Résultat' }

        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                title: 'Liste des utilisateurs'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Éditer' }
                    - { name: 'new',  label: 'Ajouter' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'email', label: 'email', type: 'email'}
                    - { property: 'username', label: 'Nom' }
                    - { property: 'password', type: 'text', label: 'Mot de passe' }
                    - { property: 'vipStatus', type: 'text', label: 'Statut VIP' }

        Website:
            class: App\Entity\Website
            label: 'Sites Web Partenaires'
            list:
                title: 'Liste des sites peb partenaires'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Éditer' }
                    - { name: 'new',  label: 'Ajouter' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'name', label: 'nom du site'}

        WebsiteUrl:
            class: App\Entity\WebsiteUrl
            label: 'Sites Web Partenaires'
            list:
                title: 'Adresses des sites web partenaires'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Éditer' }
                    - { name: 'new',  label: 'Ajouter' }
                    - { name: 'delete', icon: 'trash', label: 'Supprimer' }
            form:
                fields:
                    - { property: 'url', label: 'adresse du site'}
