easy_admin:
#    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'
    site_name: 'Craft Betting'

    design:
        assets:
            favicon: '/build/favicon/favicon.png'
        menu:
            - label: 'gérer les pronostics'
            - { entity: 'Prono', icon: 'newspaper', label: 'Pronostics' }

            - label: 'gérer les sites partenaires'
            - label: 'Sites Web et Adresses'
              icon: 'folder'
              children:
                - { entity: 'Website', icon: 'paperclip', label: 'Sites Web' }
                - { entity: 'WebsiteUrl', icon: 'link', label: 'Adresses des Sites Web' }
#
            - label: 'gérer les utilisateurs'
            - { entity: 'User', icon: 'user', label: 'Utilisateurs' }

    formats:
        date: 'd/m/Y'
        time: 'h:i'

    entities:
        Prono:
            class: App\Entity\Prono
            label: 'Pronostics'
            list:
                title: 'Liste des pronostics'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'date', label: 'Date' }
                    - { property: 'time', label: 'Horaire', format: 'H:i' }
                    - { property: 'countryAndLeague', label: 'Pays et Ligue' }
                    - { property: 'homeTeam', label: 'Domicile' }
                    - { property: 'visitorTeam', label: 'Éxterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site Web' }
                    - { property: 'websiteUrl', label: 'Adresse Site Web' }
            form:
                fields:
                    - { property: 'date', label: 'Date'}
                    - { property: 'time', label: 'Heure'}
                    - { property: 'sport', label: 'Sport' }
                    - { property: 'countryAndLeague', label: 'Championnat' }
                    - { property: 'homeTeam', label: 'Équipe à domicile' }
                    - { property: 'visitorTeam', label: 'Équipe à l''exterieur' }
                    - { property: 'result', label: 'Résultat' }
                    - { property: 'odd', label: 'Cote' }
                    - { property: 'website', label: 'Site' }
                    - { property: 'websiteUrl', label: 'Adresse du site' }
                    - { property: 'analysis', type: 'textarea',  label: 'Analyse' }

        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                title: 'Liste des utilisateurs'
            form:
                fields:
                    - { property: 'email', label: 'email', type: 'email'}
                    - { property: 'username', label: 'Nom' }
                    - { property: 'password', type: 'text', label: 'Mot de passe' }
                    - { property: 'vipStatus', type: 'text', label: 'Statut VIP' }

        Website:
            class: App\Entity\Website
            label: 'Sites Web Partenaires'
            list:
                title: 'Liste des sites peb partenaires'
            form:
                fields:
                    - { property: 'name', label: 'nom du site'}

        WebsiteUrl:
            class: App\Entity\WebsiteUrl
            label: 'Sites Web Partenaires'
            list:
                title: 'Adresses des sites web partenaires'
            form:
                fields:
                    - { property: 'url', label: 'adresse du site'}

#        - App\Entity\CountryAndLeague
#        - App\Entity\Result
#        - App\Entity\Sport
#        - App\Entity\Team
