easy_admin:
#    site_name: '<img src="https://symfony.com/logos/symfony_white_01.png" />'
    site_name: 'Craft Betting'

    design:
        assets:
            favicon: '/build/favicon/favicon.png'

    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Prono
        - App\Entity\Sport
        - App\Entity\CountryAndLeague
        - App\Entity\Team
        - App\Entity\Website
        - App\Entity\WebsiteUrl
        - App\Entity\User
